server:
  port: 0
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

spring:
  application:
    name: product-service

firestore:
  project-id: ${FIRESTORE_PROJECT_ID:kaveesha-cloud}
  products-collection: ${FIRESTORE_PRODUCTS_COLLECTION:products}

storage:
  provider: ${STORAGE_PROVIDER:gcs} # local | gcs
  local:
    base-dir: ${LOCAL_STORAGE_DIR:./data/uploads}
  gcs:
    project-id: ${GCS_PROJECT_ID:cloud-module-490703}
    bucket: ${GCS_BUCKET:juice_images}

management:
  endpoints:
    web:
      exposure:
        include: health,info